In [1]:
import numpy as np          # NumPyのインポート

In [2]:
mtx = np.array([[1, 2, 3],  # (3, 3)の行列を作成
                [4, 5, 6],  # dtypeを指定しない場合は
                [7, 8, 9]]  # 成分の値に対応した型になる
               )

In [3]:
mtx.dtype       # データの型を確認

dtype('int32')

In [4]:
mtx[0]          # 1行目のすべての成分

array([1, 2, 3])

In [5]:
mtx[0,]         # 1行目のすべての成分

array([1, 2, 3])

In [6]:
mtx[0, :]       # 1行目のすべての成分

array([1, 2, 3])

In [7]:
mtx[:, 0]       # 1列目のすべての成分

array([1, 4, 7])

In [8]:
mtx[1, 1]       # 2行、2列の成分

5

In [9]:
mtx[0:2, 0:2]   # 1行～2行、1列～2列の部分行列を抽出

array([[1, 2],
       [4, 5]])