In [1]:
import numpy as np # NumPyのインポート

In [2]:
mtx = np.array([[1, 2, 3],        # (3, 3)の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
                dtype = float)

In [3]:
print(mtx + 10)   # 足し算

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


In [4]:
print(mtx - 10)   # 引き算

[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]


In [6]:
print(mtx*2)   # 乗算

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [7]:
print(mtx/2)   # 除算

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
