In [1]:
import numpy as np  # NumPyのインポート

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y            # 要素ごとの足し算

array([5, 7, 9])

In [3]:
x - y            # 要素ごとの引き算

array([-3, -3, -3])

In [4]:
x * y            # 要素ごとの掛け算

array([ 4, 10, 18])

In [5]:
x / y            # 要素ごとの割り算

array([0.25, 0.4 , 0.5 ])