In [1]:
import numpy as np # NumPyのインポート

In [2]:
# dtypeで型を指定してベクトルを生成
x = np.array([1, 2, 3, 4, 5], dtype = float)   
# 0階テンソル（スカラー）を生成
y = np.array(10)
# ベクトルに0階テンソルを加算
print(x + y)

[11. 12. 13. 14. 15.]


In [3]:
print(x + 10)   # スカラーを加算

[11. 12. 13. 14. 15.]


In [4]:
print(x - 1)    # 減算

[0. 1. 2. 3. 4.]


In [5]:
print(x * 10)   # 乗算

[10. 20. 30. 40. 50.]


In [6]:
print(x / 2)   # 除算

[0.5 1.  1.5 2.  2.5]
