In [1]:
import numpy as np # NumPyのインポート

In [2]:
vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

In [3]:
print(vec1 + vec2)    # ベクトル同士の足し算

[50 70 90]


In [4]:
print(vec1 - vec2)    # ベクトル同士の引き算

[-30 -30 -30]


In [5]:
print(4*vec1)         # ベクトルの定数倍

[ 40  80 120]


In [6]:
print(vec1 / vec2)    # ベクトル同士の割り算

[0.25 0.4  0.5 ]
