In [ ]:
# !!!!!注意してください!!!!!
# 1～7セルはGoogleドライブの/content/drive/My\ Drive/Colab\ Notebooks/taiwa_copas/
# に格納したrest1046フォルダーにアクセスするためのサンプルコードを参考までに載せてあります
# したがいまして1～7セルは実行しないようにしてください
Google Colabで

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
ls /content/drive/My\ Drive/

'Colab Notebooks'/   MyColab/


In [ ]:
ls /content/drive/My\ Drive/Colab\ Notebooks

 cats_and_dogs_Test.ipynb   test.ipynb
 taiwa_copas/               TnsorFlow2book_5_10VGG16finetuning_one-hot.ipynb
'TensorFlow_ Hub.ipynb'     物体・画像認識と時系列データ処理第2版sample/


In [ ]:
ls /content/drive/My\ Drive/Colab\ Notebooks/taiwa_copas

rest1046/  sample5_12_Ensemble2.ipynb  taiwa_copas_class3_Ensemble.ipynb


In [ ]:
ls /content/drive/My\ Drive/Colab\ Notebooks/taiwa_copas/rest1046/

1404365812.log.json  1408003443.log.json  1408542064.log.json
1407143708.log.json  1408003627.log.json  1408542332.log.json
1407143981.log.json  1408003832.log.json  1408546133.log.json
1407149923.log.json  1408004213.log.json  1408546669.log.json
1407208809.log.json  1408007833.log.json  1408546902.log.json
1407209083.log.json  1408011443.log.json  1408547057.log.json
1407209215.log.json  1408011691.log.json  1408556093.log.json
1407209333.log.json  1408012070.log.json  1408556252.log.json
1407209477.log.json  1408012256.log.json  1408556370.log.json
1407209684.log.json  1408016515.log.json  1408556515.log.json
1407209777.log.json  1408016716.log.json  1408556696.log.json
1407209879.log.json  1408017049.log.json  1408580199.log.json
1407210003.log.json  1408017565.log.json  1408580387.log.json
1407212345.log.json  1408017917.log.json  1408584247.log.json
1407213717.log.json  1408018385.log.json  1408584303.log.json
1407213959.log.json  1408018699.log.json  1408584426.log.json
14072141

In [ ]:
cd /content/drive/My\ Drive/Colab\ Notebooks/taiwa_copas/

/content/drive/My Drive/Colab Notebooks/taiwa_copas


In [ ]:
ls

rest1046/  sample5_12_Ensemble2.ipynb  taiwa_copas_class3_Ensemble.ipynb


In [ ]:
%%time
'''
1.データの読み込み
'''
import os
import json

# コーパスのディレクトリを設定
file_path = 'rest1046/'
# ファイルの一覧を取得
file_dir = os.listdir(file_path)
# 人間の発話を保持するリスト
utterance_txt = []
# システムの応答を保持するリスト
system_txt = []
# 正解ラベルを保持するリスト
label = []

# ファイルごとに対話データを整形する
for file in file_dir:
    # JSONファイルの読み込み
    r = open(file_path + file, 'r', encoding='utf-8')
    json_data = json.load(r)
        
    # 発話データ配列から発話テキストと破綻かどうかの正解データを抽出
    for turn in json_data['turns']:
        turn_index = turn['turn-index'] # turn-indexキー(対話のインデックス)
        speaker = turn['speaker']       # speakerキー("U"人間、"S"システム)
        utterance = turn['utterance']   # utteranceキー(発話テキスト)
        
        # 先頭行(システムの冒頭の発話)以外を処理
        if turn_index != 0:
            # 人間の発話（質問）のテキストを抽出
            if speaker == 'U':
                #u_text = ''
                u_text = utterance

            # システムの応答内容が破綻かどうかを抽出
            else:
                a = ''
                sys = turn['utterance'] # システムの発話（応答）を抽出
                t = turn['annotations'][0] # １つ目のアノテーションを抽出                
                a = t['breakdown']      # アノテーションのフラグを抽出
                if a == 'O':            # O（破綻していない）を0で置換
                    val = 0
                elif a == 'T':          # T（破綻していないが違和感がある）を1で置換
                    val = 1
                else:                   # 上記以外のX（破綻している）は2で置換
                    val = 2
                # 人間の発話をリストに追加
                utterance_txt.append(u_text)
                # システムの応答をリストに追加
                system_txt.append(sys)
                # 正解ラベルをリストに追加
                label.append(str(val))

CPU times: user 427 ms, sys: 134 ms, total: 561 ms
Wall time: 5min 48s


In [ ]:
'''
2. 読み込んだデータのサイズを出力
'''
print(len(utterance_txt)) # 人間の発話のサイズ
print(len(system_txt))    # システムの応答のサイズ
print(len(label))         # 正解ラベルのサイズ

10460
10460
10460


In [ ]:
'''
3. 人間の発話を出力
'''
utterance_txt

['おはようございます',
 '軽いノリですね',
 'もっと軽い感じになりますね',
 '軽く行きましょう',
 'どうぞどうぞ',
 '雨が降らないですねえ',
 'もう少し降ってくれてもいいですねえ',
 'そうですか．涼しくなりますもんね',
 'そうですね．そろそろ一降り欲しいです',
 '水は大事です',
 '夏といえば海水浴でしょ',
 '海はいいですよね',
 '飛び込みたくなりますね',
 'ビーチバレーをしたいです',
 '海の家で食べるたこ焼きはおいしいですよね',
 'ビーチバレーはしたことないんですよ',
 'そうなのですか',
 '夏祭りに行きたいです',
 '今年はまだ花火を見ていません',
 '打ち上げ花火がやっぱり最高です',
 'こんにちは',
 'おやまあ',
 '遠慮しておきます',
 'ええ．今は休憩中です',
 '遠慮は必要です',
 'そうですね',
 'もうすぐお盆ですね',
 '帰省されますか',
 'まあそうですかね．私は帰省はしないです',
 'そうなんですか',
 'こんにちは',
 'コピットやりましょう',
 '甲州弁は面白いですね',
 'いやあー．そうですかね．ほほえましいと感じます',
 '残っていくでしょうねえ',
 '私は関西出身です',
 '関西弁はいいですねえ',
 'そうですねえ',
 '大阪と京都では言葉が違いますよ',
 '神戸もまた違いますね',
 'こんにちは',
 'さようなら',
 'ばいばい',
 'あり？',
 'そうだね',
 '何かお話ししようよ',
 'さみしいと思うよ',
 '今生の別れなら泣くと思う',
 'ばいばいは読めないね',
 'ばいばいは覚えないね',
 'こんにちは！山にも行きたいです！',
 '来週は海に行こうかと思っています',
 'いいですね！砂浜を走り回りたいです',
 'そうですよね！靴の中に砂が入るのは許せませんけどね',
 'そうだね！海に行くときは履物を選ばないといけないね',
 'サンダルとかウォーターシューズが必要ですね',
 '履き心地が良いものを選ばないと靴擦れを起こしてしまいますね',
 'そうですね！そういえば、お祭りで事故が起こっていましたね',
 'ちょっと外に出るときはサンダルは便利ですよね',
 'その分、壊れやすい気

In [ ]:
'''
4. システムの応答を出力
'''
system_txt

['ざっす',
 'ざを取るようですよ',
 'いいなあ！',
 'ざを取る予定です',
 'どうもどうも',
 '雨が少ないです',
 '雨は得意ですね',
 '雨は欲しいですね',
 '雨は大切ですね',
 '雨は優しいですね',
 '海水浴で有名ですね',
 '海はキレーですね',
 '海は透明度が良いですね',
 'ビーチバレーに興じますよねえ',
 'ビーチバレーではしゃぎますよねえ',
 'ビーチバレーは好きですね',
 'そうなのです',
 '夏祭りは楽しいですよねー',
 '線香花火がいいですね',
 '打ち上げ花火だったら連発でガンガン上がるのが楽しい',
 'ちゅっちゅ',
 'ちゅっちゅを受け取りますか',
 '遠慮はいいですね',
 '遠慮は必要ないですか',
 '遠慮のなさいいよ',
 'ありがとうございます',
 '遠慮は必要ないですよねー',
 '帰省はめんどくさいです',
 '帰省は気が重いです',
 'はい',
 'こんにちは',
 'ですね',
 '甲州弁で疲れます',
 '甲州弁を残しますよねえ',
 '甲州弁で疲れますよねー',
 '私も大好きです！',
 '関西弁は懐かしいですね',
 'うぬ',
 'うぬは力が欲しいですね',
 '神戸が良いですね',
 'さようなら',
 'また会う日まで',
 'ばいばいあり',
 'ばいばいはさみしいです',
 'うんうん',
 'ばいばいはさみしいですか',
 'ばいばいで泣きますよねー',
 'ばいばいを読みますよねー',
 'ばいばいを覚えますよねえ',
 'ばいばいは嫌です',
 '朝から海に行きますか？？',
 '気持ちがいいですね',
 '砂浜は気持ちがいいですよねー',
 '靴は大事です',
 '靴にこだわるのです',
 '履き心地が良いですね',
 'サンダルは良いですね',
 'サンダルは夏前がいいですね',
 'サンダルは通気性が良いですね',
 'サンダルは楽ですね',
 '気持ちがいいですね',
 'クーラーは心地よいですね',
 'クーラーは欲しいですね',
 'うん',
 '熱中症でぶっ倒れますよねー',
 '飲み物は麦茶がいいですよねー',
 '麦茶はいいですね',
 'プロテインだね',
 'パッション屋良を知ってませんよ',
 'パッション屋良を思い

In [ ]:
'''
5. 正解ラベルを出力
'''
label

['2',
 '2',
 '2',
 '2',
 '1',
 '1',
 '2',
 '1',
 '0',
 '2',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '2',
 '2',
 '2',
 '1',
 '1',
 '2',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '2',
 '2',
 '2',
 '0',
 '1',
 '2',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '2',
 '2',
 '1',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '2',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '2',
 '1',
 '1',
 '2',
 '0',
 '1',
 '2',
 '1',
 '0',
 '0',
 '1',
 '1',
 '2',
 '2',
 '0',
 '0',
 '2',
 '1',
 '2',
 '0',
 '1',
 '0',
 '0',
 '1',
 '2',
 '1',
 '0',
 '0',
 '0',
 '2',
 '1',
 '1',
 '1',
 '2',
 '2',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '2',
 '2',
 '2',
 '2',
 '1',
 '2',
 '1',
 '1',
 '2',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '2',
 '2',
 '1',
 '1',
 '2',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0'

In [ ]:
'''
6. 人間の発話、システムの応答、正解ラベルをデータフレームにまとめる
''' 
import pandas as pd
df = pd.DataFrame({'utterance_txt' : utterance_txt,
                   'system_txt' : system_txt,
                   'label' : label}
                 )
df   # 出力

utterance_txt    system_txt label
0                             おはようございます           ざっす     2
1                               軽いノリですね     ざを取るようですよ     2
2                         もっと軽い感じになりますね         いいなあ！     2
3                              軽く行きましょう      ざを取る予定です     2
4                                どうぞどうぞ        どうもどうも     1
...                                 ...           ...   ...
10455                              どちらに           なにが     2
10456  まあ詮索はよしとしましょう．私はカフェテリアで昼食をとる予定です       詮索は無用です     1
10457                      そうですね．そうですね．            はい     0
10458                     昼はゆっくり過ごしたいです      詮索は無用よねー     2
10459                          まあそうですねー  詮索をされるかもしれない     2

[10460 rows x 3 columns]

In [ ]:
'''
7. 破綻していない(0)、破綻していないが違和感(1)、破綻(2)をカウント
''' 
df['label'].value_counts()

0    5329
1    2937
2    2194
Name: label, dtype: int64

In [ ]:
pip install janome

     |████████████████████████████████| 19.7MB 1.3MB/s 


In [ ]:
'''
8. 形態素への分解
''' 
from janome.tokenizer import Tokenizer # janomeのパッケージをインポート
import re                              # 正規表現ライブラリ

def parse(utterance_txt):
    '''
    分かち書きを行って形態素に分解する
    '''
    t = Tokenizer()                     # Tokenizerクラスのオブジェクトを生成
    separation_tmp = []                 # 形態素を一時保存するリスト
    # 形態素に分解
    for row in utterance_txt:
        # リストから発話テキストの部分を抽出して形態素解析を実行
        tokens = t.tokenize(row)
        # 形態素の見出しの部分を取得してseparation_tmpに追加
        separation_tmp.append(
            [token.surface for token in tokens if (
                not re.match('記号', token.part_of_speech)             # 記号を除外
                and (not re.match('助詞', token.part_of_speech))       # 助詞を除外
                and (not re.match('助動詞', token.part_of_speech))     # 助動詞を除外
                )
             ])
        # 空の要素があれば取り除く
        while separation_tmp.count('') > 0:
            separation_tmp.remove('')
    return separation_tmp

# 人間の発話を形態素に分解する
df['utterance_token'] = parse(df['utterance_txt'])
# システムの応答を形態素に分解する
df['system_token'] = parse(df['system_txt'])

# 形態素への分解後のデータフレームを出力
df

utterance_txt  ...     system_token
0                             おはようございます  ...            [ざっす]
1                               軽いノリですね  ...     [ざを, 取る, よう]
2                         もっと軽い感じになりますね  ...             [いい]
3                              軽く行きましょう  ...     [ざを, 取る, 予定]
4                                どうぞどうぞ  ...       [どうも, どうも]
...                                 ...  ...              ...
10455                              どちらに  ...             [なに]
10456  まあ詮索はよしとしましょう．私はカフェテリアで昼食をとる予定です  ...         [詮索, 無用]
10457                      そうですね．そうですね．  ...             [はい]
10458                     昼はゆっくり過ごしたいです  ...         [詮索, 無用]
10459                          まあそうですねー  ...  [詮索, さ, れる, しれ]

[10460 rows x 5 columns]

In [ ]:
'''
9. 発話と応答それぞれの形態素の数をデータフレームに登録する
''' 
df['u_token_len'] = df['utterance_token'].apply(len)
df['s_token_len'] = df['system_token'].apply(len)
df

utterance_txt    system_txt  ... u_token_len s_token_len
0                             おはようございます           ざっす  ...           1           1
1                               軽いノリですね     ざを取るようですよ  ...           2           3
2                         もっと軽い感じになりますね         いいなあ！  ...           4           1
3                              軽く行きましょう      ざを取る予定です  ...           2           3
4                                どうぞどうぞ        どうもどうも  ...           2           2
...                                 ...           ...  ...         ...         ...
10455                              どちらに           なにが  ...           1           1
10456  まあ詮索はよしとしましょう．私はカフェテリアで昼食をとる予定です       詮索は無用です  ...           9           2
10457                      そうですね．そうですね．            はい  ...           2           1
10458                     昼はゆっくり過ごしたいです      詮索は無用よねー  ...           3           2
10459                          まあそうですねー  詮索をされるかもしれない  ...           2           4

[10460 rows x 7 columns]

In [ ]:
'''
10. 単語の出現回数を記録して辞書を作成
'''
from collections import Counter   # カウント処理のためのライブラリ
import itertools                   # イテレーションのためのライブラリ

# {単語：出現回数}の辞書を作成
def makedictionary(data):
    return Counter(itertools.chain(* data))

In [ ]:
'''
11. 単語を出現回数順(降順)に並べ替えて連番をふる関数
'''
def update_word_dictionary(worddic):
    word_list = []
    word_dic = {}
    # most_common()で出現回数順に要素を取得しword_listに追加
    for w in worddic.most_common():
        word_list.append(w[0])

    # 頻度順に並べた単語をキーに、1から始まる連番を値に設定
    for i, word in enumerate(word_list, start=1):
        word_dic.update({word: i})
        
    return word_dic

In [ ]:
'''
12. 単語を出現頻度の数値に置き替える関数
'''
def bagOfWords(word_dic, token):
    return [[ word_dic[word] for word in sp] for sp in token]

In [ ]:
'''
13.発話を{単語：出現回数}の辞書にする
'''
utter_word_frequency = makedictionary(df['utterance_token'])
utter_word_frequency

Counter({'おはよう': 40,
         '軽い': 5,
         'ノリ': 2,
         'もっと': 16,
         '感じ': 31,
         'なり': 115,
         '軽く': 2,
         '行き': 280,
         'どうぞ': 15,
         '雨': 70,
         '降ら': 4,
         'もう少し': 6,
         '降っ': 18,
         'くれ': 24,
         'いい': 566,
         'そう': 691,
         '涼しく': 18,
         'もん': 51,
         'そうですね': 284,
         'そろそろ': 17,
         '一': 54,
         '降り': 5,
         '欲しい': 31,
         '水': 31,
         '大事': 56,
         '夏': 154,
         'いえ': 70,
         '海水浴': 12,
         '海': 235,
         '飛び込み': 1,
         'ビーチバレー': 4,
         'し': 739,
         '家': 54,
         '食べる': 52,
         'たこ焼き': 6,
         'おいしい': 113,
         'こと': 402,
         'ない': 152,
         'ん': 777,
         'の': 598,
         '祭り': 18,
         '今年': 59,
         'まだ': 43,
         '花火': 32,
         '見': 155,
         'い': 351,
         '打ち上げ花火': 4,
         'やっぱり': 30,
         '最高': 29,
         'こんにちは': 187,
         'おや': 2,
   

In [ ]:
'''
14.応答を{単語：出現回数}の辞書にする
'''
system_word_frequency = makedictionary(df['system_token'])
system_word_frequency

Counter({'ざっす': 1,
         'ざを': 2,
         '取る': 4,
         'よう': 126,
         'いい': 847,
         '予定': 43,
         'どうも': 5,
         '雨': 123,
         '少ない': 25,
         '得意': 35,
         '欲しい': 135,
         '大切': 82,
         '優しい': 21,
         '海水浴': 12,
         '有名': 107,
         '海': 386,
         'キレー': 10,
         '透明': 19,
         '度': 25,
         '良い': 162,
         'ビーチバレー': 5,
         '興じ': 2,
         'はしゃぎ': 3,
         '好き': 452,
         'そう': 365,
         'の': 712,
         '夏': 18,
         '祭り': 12,
         '楽しい': 148,
         '線香': 15,
         '花火': 50,
         '打ち上げ花火': 7,
         '連発': 6,
         'ガンガン': 4,
         '上がる': 8,
         'ち': 26,
         'ゅっちゅ': 8,
         'ゅっちゅを': 7,
         '受け取り': 2,
         '遠慮': 5,
         '必要': 48,
         'ない': 87,
         'な': 8,
         'さ': 101,
         'ありがとう': 107,
         '帰省': 3,
         'めんどくさい': 5,
         '気': 165,
         '重い': 9,
         'はい': 93,
         'こんにちは': 25,
       

In [ ]:
'''
15.発話の単語辞書を単語の頻度順（降順）で並べ替えて連番を割り当てる
'''
utter_word_dic = update_word_dictionary(utter_word_frequency)
utter_word_dic

{'ん': 1,
 'し': 2,
 'そう': 3,
 '好き': 4,
 'の': 5,
 'いい': 6,
 '何': 7,
 'こと': 8,
 '私': 9,
 'い': 10,
 'あり': 11,
 'そうですね': 12,
 '行き': 13,
 '食べ': 14,
 '海': 15,
 'スイカ': 16,
 'てる': 17,
 'それ': 18,
 'お': 19,
 'はい': 20,
 'こんにちは': 21,
 'ある': 22,
 '気': 23,
 'する': 24,
 'いる': 25,
 '最近': 26,
 'あなた': 27,
 'よく': 28,
 'どこ': 29,
 'どう': 30,
 '見': 31,
 '夏': 32,
 'どんな': 33,
 '人': 34,
 'ない': 35,
 '今日': 36,
 '思い': 37,
 '暑い': 38,
 'ー': 39,
 'もの': 40,
 '行っ': 41,
 '良い': 42,
 '僕': 43,
 '楽しい': 44,
 'て': 45,
 'なり': 46,
 'おいしい': 47,
 '方': 48,
 '退屈': 49,
 'でも': 50,
 '行く': 51,
 'なっ': 52,
 '今': 53,
 'ほう': 54,
 'つけ': 55,
 'いや': 56,
 '大丈夫': 57,
 'ありがとう': 58,
 'さ': 59,
 'うん': 60,
 '多い': 61,
 'ください': 62,
 'れ': 63,
 '仕事': 64,
 '熱中': 65,
 '症': 66,
 '大変': 67,
 '美味しい': 68,
 'き': 69,
 'なる': 70,
 'こんばんは': 71,
 'でき': 72,
 'もう': 73,
 'よう': 74,
 '雨': 75,
 'いえ': 76,
 'やっ': 77,
 '一緒': 78,
 'とき': 79,
 '話': 80,
 '嫌い': 81,
 '確か': 82,
 'みたい': 83,
 'ゲーム': 84,
 '山': 85,
 'ちょっと': 86,
 'あまり': 87,
 '見る': 88,
 '他': 89,
 'まあ': 90,
 '今年': 91,
 'しれ'

In [ ]:
'''
16.応答の単語辞書を単語の頻度順（降順）で並べ替えて連番を割り当てる
'''
system_word_dic = update_word_dictionary(system_word_frequency)
system_word_dic

{'いい': 1,
 'の': 2,
 '好き': 3,
 'ん': 4,
 '海': 5,
 'そう': 6,
 'スイカ': 7,
 '退屈': 8,
 '症': 9,
 '熱中': 10,
 'てる': 11,
 '大好き': 12,
 'し': 13,
 '行き': 14,
 '気': 15,
 '良い': 16,
 'うん': 17,
 '多い': 18,
 'ー': 19,
 'つけ': 20,
 '楽しい': 21,
 'こと': 22,
 '欲しい': 23,
 'お': 24,
 'よう': 25,
 '心': 26,
 '雨': 27,
 '人': 28,
 '美味しい': 29,
 '大丈夫': 30,
 '一緒': 31,
 '気持ち': 32,
 '有名': 33,
 'ありがとう': 34,
 'あり': 35,
 'て': 36,
 'しれ': 37,
 '見': 38,
 'さ': 39,
 '哲学': 40,
 'い': 41,
 'はい': 42,
 '何': 43,
 'れ': 44,
 'ない': 45,
 '大切': 46,
 '予防': 47,
 '面白い': 48,
 '朝': 49,
 'する': 50,
 '趣味': 51,
 '行く': 52,
 '映画': 53,
 '高い': 54,
 '仕事': 55,
 'うまい': 56,
 '食べ': 57,
 '楽しみ': 58,
 '買い物': 59,
 '旅行': 60,
 '実': 61,
 '天気': 62,
 '一': 63,
 '行っ': 64,
 '深い': 65,
 '食べる': 66,
 'でき': 67,
 'ゲーム': 68,
 'なり': 69,
 '見る': 70,
 '行か': 71,
 '大事': 72,
 '花火': 73,
 '必要': 74,
 '音楽': 75,
 '奥': 76,
 'テレビ': 77,
 'とり': 78,
 '大きい': 79,
 'プール': 80,
 '強い': 81,
 '悪い': 82,
 '味': 83,
 '予定': 84,
 'スポーツ': 85,
 'しり': 86,
 '綺麗': 87,
 '気分': 88,
 'でる': 89,
 'どう': 90,
 'ありがと': 91,
 'クラゲ'

In [ ]:
'''
17. 辞書のサイズを変数に登録
'''
utter_dic_size = len(utter_word_dic)
system_dic_size = len(system_word_dic)
print(utter_dic_size)
print(system_dic_size)

5330
4428


In [ ]:
'''
18. 単語を出現頻度順の数値に置き換える
'''
train_utter = bagOfWords(utter_word_dic, df['utterance_token'])
train_system = bagOfWords(system_word_dic, df['system_token'])

In [ ]:
'''
19. 数値に置き換えた発話をを出力
'''
train_utter

[[135],
 [868, 1737],
 [335, 868, 177, 46],
 [1738, 13],
 [354, 354],
 [75, 1034],
 [740, 301, 232, 6],
 [3, 302, 46, 106],
 [12, 323, 97, 869, 178],
 [179, 93],
 [32, 76, 433],
 [15, 6],
 [2624, 46],
 [1035, 2],
 [15, 98, 102, 741, 47],
 [1035, 2, 8, 35, 1],
 [3, 5],
 [32, 303, 13],
 [91, 126, 166, 31, 10],
 [1036, 186, 195],
 [21],
 [1739, 90],
 [870, 2, 1037],
 [218, 53, 1740, 137],
 [870, 131],
 [12],
 [601, 355],
 [1270, 59, 63],
 [90, 3, 9, 1270, 2],
 [3, 1],
 [21],
 [2625, 273],
 [2626, 602, 107],
 [56, 661, 3, 2627, 177],
 [2628, 356],
 [9, 603, 604],
 [603, 602, 6],
 [12, 109],
 [471, 304, 515, 434],
 [2629, 233, 434],
 [21],
 [871],
 [605, 605],
 [11],
 [3],
 [7, 1038, 255],
 [1271, 132],
 [2630, 2631, 1272, 132],
 [605, 605, 1273],
 [605, 605, 742],
 [21, 85, 13],
 [1274, 15, 224, 202, 10],
 [6, 872, 2632],
 [3, 1741, 137, 1275, 516, 5, 1276],
 [3, 15, 51, 79, 2633, 1742, 120],
 [1743, 1277, 2634, 131],
 [2635, 873, 42, 40, 1742, 2636, 1278, 274],
 [12, 3, 76, 19, 303, 743, 

In [ ]:
'''
20.数値に置き換えた応答を出力 
'''
train_system

[[2582],
 [1738, 1008, 25],
 [1],
 [1738, 1008, 84],
 [807, 807],
 [27, 149],
 [27, 100],
 [27, 23],
 [27, 46],
 [27, 191],
 [354, 33],
 [5, 423],
 [5, 209, 150, 16],
 [808, 1739],
 [808, 1287],
 [808, 3],
 [6, 2],
 [222, 355, 21],
 [274, 73, 1],
 [575, 681, 1009, 504, 2, 21],
 [144, 505],
 [144, 576, 1740],
 [809, 1],
 [809, 74, 45],
 [809, 506, 39, 1],
 [34],
 [809, 74, 45],
 [1288, 810],
 [1288, 15, 456],
 [42],
 [151],
 [],
 [1289, 507, 198],
 [1289, 507, 1290],
 [1289, 507, 198],
 [184, 12],
 [1291, 507, 356],
 [223],
 [223, 357, 23],
 [2583, 16],
 [1010],
 [1741, 2584, 157],
 [275, 275, 35],
 [275, 275, 1742],
 [17, 17],
 [275, 275, 1742],
 [275, 275, 1011],
 [275, 275, 508],
 [275, 275, 577],
 [275, 275, 97],
 [49, 5, 14],
 [32, 1],
 [1743, 32, 1],
 [1292, 72],
 [1292, 2585, 2],
 [2586, 424, 16],
 [1012, 16],
 [1012, 222, 509, 1],
 [1012, 1013, 240, 16],
 [1012, 122],
 [32, 1],
 [102, 113],
 [102, 23],
 [17],
 [10, 9, 2587, 2588],
 [578, 811, 1],
 [811, 1],
 [1014],
 [1744, 1745

In [ ]:
'''
21. 発話と応答それぞれの形態素の最大数を取得
'''
UTTER_MAX_SIZE = len(sorted(train_utter, key=len, reverse=True)[0])
SYSTEM_MAX_SIZE = len(sorted(train_system, key=len, reverse=True)[0])
print(UTTER_MAX_SIZE)
print(SYSTEM_MAX_SIZE)

18
41


In [ ]:
'''
22. 単語データの配列を同一のサイズに揃える関数
'''
from tensorflow.keras.preprocessing import sequence

def padding_sequences(data, max_len):
    '''最長のサイズになるまでゼロを埋め込む
    Parameters:
      data(array): 操作対象の配列
      max_len(int): 配列のサイズ
    '''
    return sequence.pad_sequences(
        data, maxlen=max_len, padding='post',value=0.0)

In [ ]:
'''
23. 発話の単語配列のサイズを最長サイズに合わせる
'''
train_U = padding_sequences(train_utter, UTTER_MAX_SIZE)
print(train_U.shape)
print(train_U)

(10460, 18)
[[ 135    0    0 ...    0    0    0]
 [ 868 1737    0 ...    0    0    0]
 [ 335  868  177 ...    0    0    0]
 ...
 [  12    3    0 ...    0    0    0]
 [ 338  509  565 ...    0    0    0]
 [  90    3    0 ...    0    0    0]]


In [ ]:
'''
24. 応答の単語配列のサイズを最長サイズに合わせる
'''
train_S = padding_sequences(train_system, SYSTEM_MAX_SIZE)
print(train_S.shape)
print(train_S)

(10460, 41)
[[2582    0    0 ...    0    0    0]
 [1738 1008   25 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 ...
 [  42    0    0 ...    0    0    0]
 [1737 2581    0 ...    0    0    0]
 [1737   39  111 ...    0    0    0]]


In [ ]:
'''
25. 訓練データとテストデータに分割する
'''
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

# データの先頭から80パーセントを訓練データ
# 残り20パーセントをテストデータに分割する
train_df, val_df = train_test_split(
    df, train_size=0.8, shuffle=False)

# 訓練データとテストデータのデータ数を取得
train_df_num = train_df.shape[0]
val_df_num = val_df.shape[0]

# 訓練データのdictオブジェクトを作成
trainX = {
    # 人間の発話
    'utterance': train_U[:train_df_num],
    # システムの応答
    'system': train_S[:train_df_num],    
    # 人間の発話の形態素の数(int)
    'u_token_len': np.array(train_df[['u_token_len']]),
    # システムの応答の形態素の数(int)
    's_token_len': np.array(train_df[['s_token_len']])
}

# 正解ラベルをOne-hot表現のndarrayにする
trainY = to_categorical(train_df['label'], 3)

print((trainX['utterance'].shape))
print((trainX['system'].shape))
print(trainY.shape)

# テストデータのdictオブジェクトを作成
testX = {
    # 人間の発話
    'utterance': train_U[train_df_num:],
    # システムの応答
    'system': train_S[train_df_num:],
    
    # 人間の発話の形態素の数(int)
    'u_token_len': np.array(val_df[['u_token_len']]),
    # システムの応答の形態素の数(int)
    's_token_len': np.array(val_df[['s_token_len']])
}

# 正解ラベルをOne-hot表現にする
testY = to_categorical(val_df['label'], 3)

print((testX['utterance'].shape))
print((testX['system'].shape))
print(testY.shape)

y_test_label = np.array(val_df['label'], dtype= np.float_ )

(8368, 18)
(8368, 41)
(8368, 3)
(2092, 18)
(2092, 41)
(2092, 3)


In [ ]:
'''
26. モデルを構築する関数
'''
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, Conv1D, MaxPooling1D
from tensorflow.keras.layers import concatenate, Flatten, Dense, Dropout
from tensorflow.keras import models, layers, optimizers, regularizers

def create_RNN(model_num):
    """モデルを生成する

    Parameters: model_num(int):
      モデルの番号
    Returns:
      Modelオブジェクト
    """
    
    rnn_weight_decay = 0.001
    cnn_weight_decay = 0.01

    ## ------入力層------
    # 人間の発話:ユニット数は単語配列の最長サイズと同じ
    utterance = Input(shape=(UTTER_MAX_SIZE,), name='utterance')
    # システムの応答:ユニット数は単語配列の最長サイズと同じ
    system = Input(shape=(SYSTEM_MAX_SIZE,), name='system')
    # 人間の発話の単語数:ユニット数は1
    u_token_len = Input(shape=[1], name="u_token_len")
    # システムの応答の単語数:ユニット数は1
    s_token_len = Input(shape=[1], name="s_token_len")

    # ------Embedding層------
    # 人間の発話: 入力は単語の総数+100、出力の次元数は64
    emb_utterance = Embedding(
        input_dim=utter_dic_size+100,  # 発話の単語数+100
        output_dim=64,                 # 出力の次元数はReccuurent層のユニット数
        )(utterance)
    # システムの応答: 入力は単語の総数+100、出力の次元数は128
    emb_system = Embedding(
        input_dim=system_dic_size+100, # 応答の単語数+100
        output_dim=64                  # 出力の次元数はReccuurent層のユニット数
        )(system)
    # 人間の発話の単語数のEmbedding
    emb_u_len = Embedding(
        input_dim=UTTER_MAX_SIZE+1,    # 入力の次元は発話の形態素数の最大値+1
        output_dim=5                   # 出力は5
        )(u_token_len)
    # システムの応答の単語数のEmbedding
    emb_s_len = Embedding(
        input_dim=SYSTEM_MAX_SIZE+1,   # 入力の次元は応答の形態素数の最大値+1
        output_dim=5                   # 出力は5
        )(s_token_len)

    # ------RNN------
    if model_num < 8:
        # 人間の発話を入力
        # LSTMユニット×64 正則化あり
        layer1_1 = LSTM(64, return_sequences=True, dropout=0.5,
                        kernel_regularizer=regularizers.l2(rnn_weight_decay))(emb_utterance)
        # LSTMユニット×128 正則化あり
        layer1_final = LSTM(128, return_sequences=False, dropout=0.5,
                            kernel_regularizer=regularizers.l2(rnn_weight_decay))(layer1_1)

        # システムの応答を入力
        # LSTMユニット×64 正則化あり
        layer2_1 = LSTM(64, return_sequences=True, dropout=0.1,
                        kernel_regularizer=regularizers.l2(rnn_weight_decay))(emb_system)
        # LSTMユニット×128 正則化あり
        layer2_final = LSTM(128, return_sequences=False, dropout=0.1,
                            kernel_regularizer=regularizers.l2(rnn_weight_decay))(layer2_1)
    # ------CNN------
    else:
        # 人間の発話を入力
        # 畳み込み層1 フィルター数64 正則化あり
        layer1_1 = Conv1D(filters=64,kernel_size=(5), padding='same', activation='relu',
                          kernel_regularizer=regularizers.l2(cnn_weight_decay))(emb_system)
        # 畳み込み層2 フィルター数128 正則化あり
        layer1_2 = Conv1D(filters=128,kernel_size=(5), padding='same', activation='relu',
                          kernel_regularizer=regularizers.l2(cnn_weight_decay))(layer1_1)
        # プーリング層、ドロップアウト
        layer1_3 = MaxPooling1D(pool_size=2, strides=2, padding='same')(layer1_2)
        layer1_final = Dropout(0.5)(layer1_3)

        # システムの応答を入力
        # 畳み込み層1 フィルター数64 正則化あり
        layer2_1 = Conv1D(filters=64,kernel_size=(5), padding='same', activation='relu',
                         kernel_regularizer=regularizers.l2(cnn_weight_decay))(emb_utterance)

        # 畳み込み層2 フィルター数128 正則化あり
        layer2_2 = Conv1D(filters=128,kernel_size=(5), padding='same', activation='relu',
                             kernel_regularizer=regularizers.l2(cnn_weight_decay))(layer2_1)
        # プーリング層、ドロップアウト
        layer2_3 = MaxPooling1D(pool_size=2, strides=2, padding='same')(layer2_2)
        layer2_final = Dropout(0.5)(layer2_3)
        
    # ------全結合層------
    main_l = concatenate([
        Flatten()(emb_u_len),    # 人間の発話の単語数のEmbedding
        Flatten()(emb_s_len),    # システム応答の単語数のEmbedding
        Flatten()(layer1_final), # 人間の発話のRNNまたはCNNからの出力
        Flatten()(layer2_final)  # システム応答のRNNまたはCNNからの出力
    ])

    # ------512、256、128ユニットの層を追加------
    main_l = Dropout(0.5)(
        Dense(512,kernel_initializer='normal',activation='relu')(main_l))
    main_l = Dropout(0.5)(
        Dense(256,kernel_initializer='normal',activation='relu')(main_l))
    main_l = Dropout(0.5)(
        Dense(128,kernel_initializer='normal',activation='relu')(main_l))

    # ------出力層(3ユニット)------
    output = Dense(units=3,              # 出力層のニューロン数＝3
                   activation='softmax'  # 活性化はソフトマックス関数
                   )(main_l)


    # Modelオブジェクトの生成
    model = models.Model(
        # 入力層はマルチ入力モデルなのでリストにする
        inputs=[utterance, system, u_token_len, s_token_len],
        # 出力層
        outputs=output
    )
    
    return model

In [ ]:
'''
27. アンサンブルを実行する関数
'''
from scipy.stats import mode

def ensemble_majority(models, X, data_num):
    """多数決をとるアンサンブル

    Parameters:
        models(list) : Modelオブジェクトのリスト
        X(array)     : 検証用のデータ
        data_num(int): データ数
    Returns:
        各画像の正解ラベルを格納した(10000)のnp.ndarray
    """
    # (データ数,モデル数)のゼロ行列を作成
    pred_labels = np.zeros((data_num,     # 行数はデータの数
                            len(models))) # 列数はモデルの数
    # modelsからインデックス値と更新をフリーズされたモデルを取り出す
    for i, model in enumerate(models):
        # モデルごとの予測確率(データ数,クラス数)の各行(axis=1)から
        # 最大値のインデックスをとって、(データ数,モデル数)の
        # モデル列の各行にデータの数だけ格納する
        pred_labels[:, i] = np.argmax(model.predict(X), axis=1)
    # mode()でpred_labelsの各行の最頻値のみを[0]指定で取得する
    # (データ数,1)の形状をravel()で(,データ数)の形状にフラット化する    
    return np.ravel(mode(pred_labels, axis=1)[0])

In [ ]:
'''
28. 複数のモデルで学習し、アンサンブルによる評価を行う関数
'''
import math
import numpy as np
from sklearn.metrics import accuracy_score
from keras.callbacks import LearningRateScheduler
from keras.callbacks import History
from tensorflow.keras import models, layers, optimizers, regularizers

def train(trainX, trainY, testX, testY, y_test_label):
    """学習を行う
    
    Parameters:
        trainX(ndarray): 訓練データ
        trainY(ndarray): 訓練データの正解ラベル(One-Hot表現)
        testX(ndarray): 検証データ
        testY(ndarray): 検証データの正解ラベル(One-Hot表現)
        y_test_label(ndarray): テストデータの正解ラベル(整数値)
    """
    n_estimators = 15 # アンサンブルするモデルの数
    batch_size = 64   # ミニバッチの数
    epoch = 3         # エポック数   
    models = []       # モデルを格納するリスト
    # 各モデルの学習履歴を保持するdict
    history_all = {"hists":[], "ensemble_test":[]}
    # 各モデルの推測結果を登録する2階テンソルを0で初期化
    # (データ数, モデル数)
    model_predict = np.zeros((val_df_num,   # 行数は検証データの数
                             n_estimators)) # 列数はネットワークの数

    # モデルの数だけ繰り返す
    for i in range(n_estimators):
        # 何番目のモデルかを表示
        print('Model',i+1)
        # CNNのモデルを生成,引数はモデルの番号
        train_model = create_RNN(i)
        #train_model.summary()
        # モデルをコンパイルする
        train_model.compile(optimizer=optimizers.Adam(lr=0.001),
                            loss='categorical_crossentropy',
                            metrics=["acc"])
        # コンパイル後のモデルをリストに追加
        models.append(train_model)

        # コールバックに登録するHistoryオブジェクトを生成
        hist = History()

        # 学習を行う
        train_model.fit(
            trainX, trainY,        # 訓練データ、正解ラベル
            batch_size=batch_size, # ミニバッチのサイズ
            epochs=epoch,          # 学習回数
            verbose=1,             # 学習の進捗状況を出力する
            callbacks=[hist]
            )

        # テストデータで推測し、対話データごとにラベルの最大値を求め、
        # 対象のインデックスを正解ラベルとしてsingle_predsのi列に格納
        model_predict[:, i] = np.argmax(train_model.predict(testX),
                                       axis=-1) # 行ごとの最大値を求める

        # 学習に用いたモデルの学習履歴をglobal_histのhistsキーに登録
        history_all['hists'].append(hist.history)
        
        # 平均をとるアンサンブルを実行
        ensemble_test_pred = ensemble_majority(models, testX, val_df_num)
        
        # scikit-learn.accuracy_score()でアンサンブルによる精度を取得
        ensemble_test_acc = accuracy_score(y_test_label, ensemble_test_pred)
        
        # アンサンブルの精度をhistory_allのensemble_testキーに追加
        history_all['ensemble_test'].append(ensemble_test_acc)
        # 現在のアンサンブルの精度を出力
        print('Current Ensemble Test Accuracy : ', ensemble_test_acc)

In [ ]:
%%time
# アンサンブルを実行
train(trainX, trainY, testX, testY, y_test_label)

Model 1
Epoch 1/3
131/131 [==============================] - 10s 20ms/step - loss: 1.2821 - acc: 0.5047
Epoch 2/3
131/131 [==============================] - 3s 20ms/step - loss: 1.0203 - acc: 0.5187
Epoch 3/3
131/131 [==============================] - 3s 19ms/step - loss: 0.9591 - acc: 0.5380
Current Ensemble Test Accuracy :  0.4588910133843212
Model 2
Epoch 1/3
131/131 [==============================] - 7s 20ms/step - loss: 1.2761 - acc: 0.4989
Epoch 2/3
131/131 [==============================] - 3s 20ms/step - loss: 1.0334 - acc: 0.5107
Epoch 3/3
131/131 [==============================] - 3s 20ms/step - loss: 0.9625 - acc: 0.5490
Current Ensemble Test Accuracy :  0.4765774378585086
Model 3
Epoch 1/3
131/131 [==============================] - 7s 20ms/step - loss: 1.2827 - acc: 0.5038
Epoch 2/3
131/131 [==============================] - 3s 20ms/step - loss: 1.0391 - acc: 0.5016
Epoch 3/3
131/131 [==============================] - 3s 20ms/step - loss: 0.9582 - acc: 0.5438
Current Ensemb