In [1]:
import numpy as np               # NumPyをインポート

def create_matrix(x):
    '''データx1、x2にバイアスに対応するx0(=1)を加えた行列を作成
    ------------------------
    Parameters:
      x(ndarray): x1、x2を格納した2階テンソル
    '''
    x0 = np.ones([x.shape[0], 1]) # バイアスに対応する1の項(x0)を生成
                                  # 形状は(4, 1)の2階テンソル
    return np.hstack([x0, x])    # x0の(4, 1)の2階テンソルにx1,x2の2階テンソルを
                                  # 水平方向に連結して(4, 3)の2階テンソルを返す

def sigmoid(X, parameter):
    '''シグモイド関数
    ------------------------
    Parameters:
      X(ndarray): x0、x1、x2を格納した2階テンソル
      parameter(ndarray): バイアス、w1、w2を格納した1階テンソル
    Returns:
      シグモイド関数適用後のX
    '''
    return 1 / (1 + np.exp(-np.dot(X, parameter)))

def logistic_regression(X, t):
    '''二値分類を行う単純パーセプトロン
    ------------------------
    Parameters:
        X(ndarray): x0、x1、x2が格納された2階テンソル
        t(ndarray): 正解ラベルが格納された1階テンソル
    '''
    LNR = 1e-1                    # 学習率を0.1に設定
    loop = 50                     # 学習回数
    count = 1                     # 学習回数をカウントする変数
    parameter = np.random.rand(3) # バイアス,w1,w2を0〜1の一様乱数で初期化

    for i in range(loop):         # 学習をloop回繰り返す
        # バイアス,w1,w2を勾配降下法で更新
        parameter = parameter - LNR*np.dot(
            sigmoid(X,parameter) - t, X)
        # 最初の1回と以降10回ごとにパラメーターの値を出力
        if (count == 1 or count % 10 == 0):
            print('{}回: parameter = {}'.format(count, parameter))        
        count += 1               # カウンター変数の値を1増やす
        
    return parameter             # 学習後のバイアス、w1、w2を返す

In [2]:
# ANDゲート
# x1、x2の4セットを行列x(ndarray)に代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに代入
t = np.array([0, 0, 0, 1])
# xにバイアス対応の1の項を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.24334882 0.59954839 0.28255669]
10回: parameter = [-0.7255737   0.45800199  0.20390593]
20回: parameter = [-1.19401092  0.60584452  0.40470014]
30回: parameter = [-1.51198817  0.7982333   0.63694006]
40回: parameter = [-1.7802407   0.98244037  0.85221364]
50回: parameter = [-2.02154388  1.15147686  1.04575475]


In [3]:
# 学習した重み・バイアスを使ってANDゲートの出力を表示してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
         parameter  # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

array([0, 0, 0, 1])

In [4]:
# NANDゲート
# x1、x2の4セットを行列x(ndarray)に代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに代入
t = np.array([1, 1, 1, 0])
# xにバイアス対応の1の項を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.26967246 0.49521791 0.82502796]
10回: parameter = [0.49151619 0.09873724 0.37065311]
20回: parameter = [ 0.81684735 -0.22645882 -0.00903672]
30回: parameter = [ 1.1382736  -0.48914811 -0.31519654]
40回: parameter = [ 1.43413399 -0.71410138 -0.57442527]
50回: parameter = [ 1.70360676 -0.91226096 -0.79959118]


In [5]:
# 学習した重み・バイアスを使ってNANDゲートの出力を表示してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
         parameter  # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

array([1, 1, 1, 0])

In [6]:
# ORゲート
# x1、x2の4セットを行列x(ndarray)に代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに代入
t = np.array([0, 1, 1, 1])
# xにバイアス対応の1の項を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.65133856 0.94685687 0.76949455]
10回: parameter = [0.46660808 1.1651788  1.00984638]
20回: parameter = [0.27639911 1.38620315 1.25161325]
30回: parameter = [0.10576948 1.58988468 1.47281465]
40回: parameter = [-0.04618058  1.77918952  1.67694853]
50回: parameter = [-0.18179364  1.95603861  1.8663688 ]


In [7]:
# 学習した重み・バイアスを使ってORゲートの出力を表示してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
         parameter  # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

array([0, 1, 1, 1])